<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Clinical and Genomic Characterization of Secondary Rectal Cancer After Radiotherapy for Prostate Cancer – cbio-kb</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-89af0c2d685ccb09a4d7d65decb66752.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../site-styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">cbio-kb</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../papers/index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../genes/index.html"> 
<span class="menu-text">Genes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cancer_types/index.html"> 
<span class="menu-text">Cancers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../datasets/index.html"> 
<span class="menu-text">Datasets</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../drugs/index.html"> 
<span class="menu-text">Drugs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../methods/index.html"> 
<span class="menu-text">Methods</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../themes/index.html"> 
<span class="menu-text">Themes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../experiments/index.html"> 
<span class="menu-text">Experiments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ask.html"> 
<span class="menu-text">Ask</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tldr" id="toc-tldr" class="nav-link active" data-scroll-target="#tldr">TL;DR</a></li>
  <li><a href="#cohort-data" id="toc-cohort-data" class="nav-link" data-scroll-target="#cohort-data">Cohort &amp; data</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings">Key findings</a></li>
  <li><a href="#genes-alterations" id="toc-genes-alterations" class="nav-link" data-scroll-target="#genes-alterations">Genes &amp; alterations</a></li>
  <li><a href="#clinical-implications" id="toc-clinical-implications" class="nav-link" data-scroll-target="#clinical-implications">Clinical implications</a></li>
  <li><a href="#limitations-open-questions" id="toc-limitations-open-questions" class="nav-link" data-scroll-target="#limitations-open-questions">Limitations &amp; open questions</a></li>
  <li><a href="#citations-from-this-paper-used-in-the-wiki" id="toc-citations-from-this-paper-used-in-the-wiki" class="nav-link" data-scroll-target="#citations-from-this-paper-used-in-the-wiki">Citations from this paper used in the wiki</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/jim-bo/cbio-kb/edit/main/papers/40100215.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/jim-bo/cbio-kb/blob/main/papers/40100215.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Clinical and Genomic Characterization of Secondary Rectal Cancer After Radiotherapy for Prostate Cancer</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Dana M Omer </p>
             <p>Farheen Shah </p>
             <p>Anisha Luthra </p>
             <p>Chin-Tung Chen </p>
             <p>Christina I Lee </p>
             <p>Hannah Williams </p>
             <p>Henry Walch </p>
             <p>Floris S Verheij </p>
             <p>Roni Rosen </p>
             <p>Janet Alvarez </p>
             <p>Canan Firat </p>
             <p>Georgios Karagkounis </p>
             <p>Martin R Weiser </p>
             <p>Maria Widmar </p>
             <p>Iris H Wei </p>
             <p>Emmanouil P Pappou </p>
             <p>Garrett M Nash </p>
             <p>J Joshua Smith </p>
             <p>Walid K Chatila </p>
             <p>Paul B Romesser </p>
             <p>Jinru Shia </p>
             <p>Philip B Paty </p>
             <p>Julio Garcia-Aguilar </p>
             <p>Francisco Sanchez-Vega </p>
          </div>
  </div>
    
  
    
    <div>
    <div class="quarto-title-meta-heading">Doi</div>
    <div class="quarto-title-meta-contents">
      <p class="doi">
        <a href="https://doi.org/10.1001/jamanetworkopen.2025.1039">10.1001/jamanetworkopen.2025.1039</a>
      </p>
    </div>
  </div>
  </div>
  


</header>


<p><strong>PMID:</strong> 40100215 · <strong>DOI:</strong> 10.1001/jamanetworkopen.2025.1039 · <strong>Journal:</strong> JAMA Network Open (2025)</p>
<section id="tldr" class="level2">
<h2 class="anchored" data-anchor-id="tldr">TL;DR</h2>
<p>This single-institution case-control study from Memorial Sloan Kettering Cancer Center (MSKCC) looked at 64 men who developed rectal adenocarcinoma (<a href="../cancer_types/READ.html">READ</a>) 5 or more years after radiotherapy (RT) for prostate cancer (<a href="../cancer_types/PRAD.html">PRAD</a>). The paper calls these secondary rectal cancers (<code>SRC</code>; the page spells the term out to avoid confusion with the <em>SRC</em> gene) and compares them with primary rectal cancers (PRC) treated at MSKCC from 1994 to 2022 <a href="../papers/40100215.html">PMID:40100215</a>. Patients with secondary rectal cancer were much older (median 78 vs 55 years). Their tumors were smaller, earlier-stage, and more often distal and on the anterior rectal wall. They received neoadjuvant therapy less often, and they had worse 5-year overall, disease-free, and distant recurrence-free survival than 1:1 propensity-matched men with PRC. After adjusting for treatment, secondary status was independently associated with worse disease-free survival (DFS) and distant recurrence-free survival (DRFS), but not with overall survival (OS). Targeted sequencing with <a href="../methods/msk-impact-panel.html">MSK-IMPACT</a> (31 secondary vs 541 primary tumors) showed lower tumor mutational burden (TMB), fewer <a href="../genes/APC.html">APC</a> and Wnt-pathway alterations, and more <a href="../genes/SMAD4.html">SMAD4</a> inactivation. <a href="../methods/whole-exome-seq.html">Whole-exome sequencing</a> (17 vs 28 tumors) showed more frameshift deletions, inframe deletions, and splice-site variants, but no COSMIC signature differed between groups. The authors suggest, as an untested hypothesis, that these patients might benefit from immunotherapy <a href="../papers/40100215.html">PMID:40100215</a>.</p>
</section>
<section id="cohort-data" class="level2">
<h2 class="anchored" data-anchor-id="cohort-data">Cohort &amp; data</h2>
<ul>
<li><strong>Setting:</strong> retrospective case-control study at MSKCC. Patients were treated between February 1, 1994 and “September 31, 2022” (date as printed). The study followed the STROBE reporting guideline and was approved by the institutional review board, with informed consent <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>How secondary cases were selected:</strong> 498 patients had colorectal adenocarcinoma and a history of prostate cancer. Of these, 64 had an adenocarcinoma 12 cm or less from the anal verge, diagnosed at least 5 years after RT for prostate cancer ended. These 64 were classified as secondary rectal cancer (100% male; median age 78 [IQR 72–82] years) <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>Prostate RT exposure (n=64):</strong>
<ul>
<li>Modality: external beam RT (EBRT) in 31 (48.4%), interstitial brachytherapy in 19 (29.7%), and both in 14 (21.9%).</li>
<li>Median dose: 7560 cGy (IQR 5040–7560) for EBRT and 14,400 cGy for brachytherapy.</li>
<li>Median latency from end of RT to rectal cancer diagnosis: 11.50 years (IQR 7.00–17.25).</li>
<li>Median follow-up after rectal cancer diagnosis: 2.38 years (IQR 1.97–3.26) <a href="../papers/40100215.html">PMID:40100215</a>.</li>
</ul></li>
<li><strong>Primary rectal cancer controls:</strong>
<ul>
<li>843 patients with rectal cancer and no history of prostate cancer or pelvic RT (231 female [27.4%], 612 male [72.6%]).</li>
<li>The clinical reference set is 604 male PRC patients (median age 55 [IQR 46–66] years). The text does not explain the difference between 612 and 604 men.</li>
<li>Outcomes were compared against 64 men with PRC, matched 1:1 by propensity score <a href="../papers/40100215.html">PMID:40100215</a>.</li>
</ul></li>
<li><strong>Targeted sequencing:</strong>
<ul>
<li>Assay: <a href="../methods/msk-impact-panel.html">MSK-IMPACT</a>, described as covering “341 to 505 cancer-associated genes” (panel versions <a href="../methods/IMPACT341.html">IMPACT341</a> through <a href="../methods/IMPACT505.html">IMPACT505</a>).</li>
<li>Samples: 31 secondary tumors, compared with 541 PRC tumors (223 female, 318 male) and with 62 PRC tumors matched 1:2 by propensity score. The genomic matching did not include sex.</li>
<li>Germline filtering for the 31 secondary tumors used matched blood for 24 (77.4%), adjacent normal tissue for 3 (9.7%), and pooled normal DNA for 4 (12.9%) <a href="../papers/40100215.html">PMID:40100215</a>.</li>
</ul></li>
<li><strong>Whole-exome sequencing:</strong> 17 of the 31 secondary tumors (54.8%) had enough material for WES recapture, at ×150 depth for tumors and ×70 for normals (blood normals for 14 patients, adjacent non-cancer tissue for 3). They were compared with WES from 28 PRC tumors <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>Analysis pipeline:</strong>
<ul>
<li>TMB was defined as nonsynonymous mutations per megabase sequenced. Fraction of genome altered was defined using a |log2| copy-number threshold above 0.2.</li>
<li>Tools: <a href="../methods/facets.html">FACETS</a> for allele-specific copy number, <a href="../methods/msisensor.html">MSIsensor</a> for MSI (score threshold ≥10), <a href="../methods/oncokb.html">OncoKB</a> to classify variants as oncogenic, the MSKCC <a href="../methods/tempo.html">TEMPO</a> pipeline for WES, and COSMIC v3 <a href="../methods/mutational-signatures.html">mutational signatures</a>.</li>
<li>Statistics: R 4.3.2; Wilcoxon rank-sum and Fisher exact tests; Benjamini-Hochberg correction (significance at q&lt;0.10); <a href="../methods/propensity-score-matching.html">propensity score matching</a> with the MatchIt nearest-neighbor method; <a href="../methods/kaplan-meier.html">Kaplan-Meier</a> curves with log-rank tests; and <a href="../methods/cox-proportional-hazards.html">Cox</a> models stratified by clinical stage <a href="../papers/40100215.html">PMID:40100215</a>.</li>
</ul></li>
<li><strong>Propensity-matching variables:</strong> sex, age at rectal cancer diagnosis, stage, distance from the anal verge, tumor size, and circumferential tumor location. The 1:2 genomic matching used the same variables except sex <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>cBioPortal dataset:</strong> <a href="../datasets/rectal_radiation_msk_2024.html">rectal_radiation_msk_2024</a>. cBioPortal study metadata (not the paper) lists 48 rectal adenocarcinoma samples, WES plus MSK-IMPACT, on hg19. That number matches 31 IMPACT + 17 WES secondary-tumor samples, but this reading is an inference: the paper does not say which samples were deposited.</li>
</ul>
</section>
<section id="key-findings" class="level2">
<h2 class="anchored" data-anchor-id="key-findings">Key findings</h2>
<p><strong>Clinical presentation (64 secondary vs 604 male PRC)</strong> <a href="../papers/40100215.html">PMID:40100215</a></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature</th>
<th>Secondary</th>
<th>Primary (PRC)</th>
<th>P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Median age</td>
<td>78 years</td>
<td>55 years</td>
<td>&lt;.001</td>
</tr>
<tr class="even">
<td>Stage I</td>
<td>15/54 (27.8%)</td>
<td>30/604 (5.0%)</td>
<td>&lt;.001</td>
</tr>
<tr class="odd">
<td>Stage III</td>
<td>16/54 (29.6%)</td>
<td>370/604 (61.3%)</td>
<td>&lt;.001</td>
</tr>
<tr class="even">
<td>Stage IV</td>
<td>6/54 (11.1%)</td>
<td>129/604 (21.3%)</td>
<td>&lt;.001</td>
</tr>
<tr class="odd">
<td>Clinically node-positive</td>
<td>22/54 (40.7%)</td>
<td>465/574 (81.0%)</td>
<td>&lt;.001</td>
</tr>
<tr class="even">
<td>Median tumor size</td>
<td>3.50 cm</td>
<td>4.60 cm</td>
<td>&lt;.001</td>
</tr>
<tr class="odd">
<td>Tumor &lt;4 cm</td>
<td>32/55 (58.2%)</td>
<td>176/554 (31.8%)</td>
<td>&lt;.001</td>
</tr>
<tr class="even">
<td>Distal rectum</td>
<td>37/63 (58.7%)</td>
<td>131/581 (22.5%)</td>
<td>&lt;.001</td>
</tr>
<tr class="odd">
<td>Anterior wall</td>
<td>20/57 (35.1%)</td>
<td>67/496 (13.6%)</td>
<td>&lt;.001</td>
</tr>
<tr class="even">
<td>Posterior wall</td>
<td>16/57 (28.1%)</td>
<td>60/496 (12.1%)</td>
<td>&lt;.001</td>
</tr>
<tr class="odd">
<td>Fully circumferential</td>
<td>4/57 (7.0%)</td>
<td>142/496 (28.6%)</td>
<td>&lt;.001</td>
</tr>
</tbody>
</table>
<p>Stage P values are for the full stage distribution. The abstract gives 13.5% for the anterior-wall PRC figure; Table 1 and the Results give 13.6%.</p>
<p><strong>Treatment</strong> <a href="../papers/40100215.html">PMID:40100215</a></p>
<ul>
<li>Neoadjuvant therapy (NAT) was given to 33/64 (51.6%) secondary vs 570/604 (94.4%) primary patients (P&lt;.001).</li>
<li>Type of NAT differed (P&lt;.001):
<ul>
<li>Secondary: chemotherapy only was the most common (19/33, 57.6%), total NAT 13 (39.4%), chemoradiation only 1 (3%).</li>
<li>Primary: total NAT 503 (88.2%), chemotherapy only 59 (10.4%), chemoradiation only 8 (1.4%).</li>
</ul></li>
<li>Re-irradiation was not used before 2014 and became common afterwards. All 11 secondary patients who received NAT up to 2014 had chemotherapy only. After 2014, 14 of 22 (63.6%) received re-irradiation.</li>
<li>Among the 33 who received NAT:
<ul>
<li>4 (12.1%) did not complete it.</li>
<li>6 (18.2%) had grade 3 toxic effects, with no grade 4 or 5 events.</li>
<li>Watch-and-wait was offered at similar rates: 7/33 (21.2%) secondary vs 163/570 (28.6%) primary.</li>
</ul></li>
<li>Among NAT recipients who had surgery, the type of operation differed (P&lt;.001):</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Procedure</th>
<th>Secondary (of 12)</th>
<th>Primary (of 341)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Abdominoperineal resection</td>
<td>6 (50.0%)</td>
<td>85 (24.9%)</td>
</tr>
<tr class="even">
<td>Pelvic exenteration</td>
<td>2 (16.7%)</td>
<td>5 (1.5%)</td>
</tr>
<tr class="odd">
<td>Local excision</td>
<td>1 (8.3%)</td>
<td>12 (3.5%)</td>
</tr>
<tr class="even">
<td>Low anterior resection</td>
<td>3 (25.0%)</td>
<td>239 (70.1%)</td>
</tr>
</tbody>
</table>
<ul>
<li>Among NAT recipients, 14 (42.4%) secondary vs 66 (11.6%) primary patients were not candidates for oncologic resection (“Other” category).</li>
</ul>
<p><strong>Oncologic outcomes (64 secondary vs 64 propensity-matched male PRC)</strong> <a href="../papers/40100215.html">PMID:40100215</a></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>5-year outcome</th>
<th>Secondary</th>
<th>Matched PRC</th>
<th>Log-rank P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Overall survival</td>
<td>45.7%</td>
<td>64.9%</td>
<td>.01</td>
</tr>
<tr class="even">
<td>Disease-free survival</td>
<td>40.3%</td>
<td>71.2%</td>
<td>.006</td>
</tr>
<tr class="odd">
<td>Distant recurrence-free survival</td>
<td>60.8%</td>
<td>89.8%</td>
<td>.01</td>
</tr>
<tr class="even">
<td>Local recurrence-free survival</td>
<td>92.6%</td>
<td>95.3%</td>
<td>.50 (no difference)</td>
</tr>
</tbody>
</table>
<ul>
<li>Stage IV patients were excluded from the DFS and DRFS curves.</li>
<li>In Cox models stratified by clinical stage and adjusted for neoadjuvant chemotherapy, neoadjuvant chemoradiotherapy, and surgical resection, secondary status was associated with:
<ul>
<li>DFS: HR 6.16 (95% CI 2.10–18.07; P&lt;.001).</li>
<li>DRFS: HR 12.68 (95% CI 3.06–52.47; P&lt;.001).</li>
<li>OS: no significant association (HR 1.95, 95% CI 0.58–6.60; P=.28).</li>
</ul></li>
<li>Surgery was the only factor associated with OS (HR 0.38, 95% CI 0.16–0.88; P=.02). The Results text calls this “shorter OS”, which conflicts with an HR below 1 (see Limitations).</li>
</ul>
<p><strong>Targeted-sequencing genomics (31 secondary vs 541 PRC vs 62 matched PRC)</strong> <a href="../papers/40100215.html">PMID:40100215</a></p>
<ul>
<li>The paper reports no MSI or <a href="../genes/POLE.html">POLE</a> hypermutation among the profiled patients.</li>
<li>TMB was lower in secondary tumors (median 4.4 [IQR 3.2–6.7] mut/Mb) than in all PRC (5.8 [4.4–7.0]; P=.047) and matched PRC (6.1 [5.2–8.1]; P=.006).</li>
<li>There was no significant difference in fraction of genome altered, whole-genome duplication frequency, genome-wide copy-number patterns, or arm-level changes.</li>
<li>Oncogenic driver alterations (drivers altered in ≥10% of either cohort):</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Alteration</th>
<th>Secondary</th>
<th>All PRC</th>
<th>P</th>
<th>Matched PRC</th>
<th>P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="../genes/APC.html">APC</a> inactivation</td>
<td>15/31 (48.4%)</td>
<td>432/541 (79.9%)</td>
<td>&lt;.001</td>
<td>45/62 (72.6%)</td>
<td>.04</td>
</tr>
<tr class="even">
<td><a href="../genes/SMAD4.html">SMAD4</a> inactivation</td>
<td>8/31 (25.8%)</td>
<td>54/541 (10.0%)</td>
<td>.01</td>
<td>5/62 (8.1%)</td>
<td>.03</td>
</tr>
<tr class="odd">
<td>Wnt pathway (driven by <a href="../genes/APC.html">APC</a>)</td>
<td>17/31 (54.8%)</td>
<td>450/541 (83.2%)</td>
<td>&lt;.001</td>
<td>not reported</td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Whole-exome sequencing (17 secondary vs 28 PRC)</strong> <a href="../papers/40100215.html">PMID:40100215</a></p>
<ul>
<li>SBS1 (clock-like, age-associated) was the most common signature. No COSMIC signature differed in detection frequency between groups, including the mismatch-repair signatures SBS6 and SBS15. A signature counted as detected if it explained at least 10% of a sample’s mutations with detection P&lt;.05.</li>
<li>Variant counts (medians, secondary vs PRC):</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variant class</th>
<th>Secondary</th>
<th>PRC</th>
<th>P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Frameshift deletions</td>
<td>5.0 (IQR 4.0–9.0)</td>
<td>2.5 (IQR 1.0–4.2)</td>
<td>&lt;.001</td>
</tr>
<tr class="even">
<td>Inframe deletions</td>
<td>1.0 (IQR 1.0–2.0)</td>
<td>1.0 (IQR 0.0–1.0)</td>
<td>.03</td>
</tr>
<tr class="odd">
<td>Splice-site variants</td>
<td>2.0 (IQR 1.0–3.0)</td>
<td>1.0 (IQR 0.0–2.0)</td>
<td>.02</td>
</tr>
<tr class="even">
<td>Total variants</td>
<td>122.0</td>
<td>138.0</td>
<td>.72</td>
</tr>
<tr class="odd">
<td>Missense variants</td>
<td>70.0</td>
<td>85.5</td>
<td>.54</td>
</tr>
</tbody>
</table>
<ul>
<li>The authors link the excess deletions to RT-induced double-strand breaks that are repaired incorrectly, consistent with earlier reports of deletion-rich radiation-associated tumors.</li>
</ul>
</section>
<section id="genes-alterations" class="level2">
<h2 class="anchored" data-anchor-id="genes-alterations">Genes &amp; alterations</h2>
<ul>
<li><a href="../genes/APC.html">APC</a>: inactivating somatic alterations were less frequent in secondary rectal cancer: 48.4% vs 79.9% in all PRC (P&lt;.001) and 72.6% in matched PRC (P=.04). This lower APC rate drives the drop in Wnt-pathway alterations (54.8% vs 83.2%, P&lt;.001). The authors note that APC wild-type status has been linked to more aggressive colorectal tumors, which could help explain the worse outcomes <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><a href="../genes/SMAD4.html">SMAD4</a>: inactivation was enriched in secondary rectal cancer: 25.8% vs 10.0% in all PRC (P=.01) and 8.1% in matched PRC (P=.03). The authors also cite <a href="../genes/SMAD4.html">SMAD4</a> alterations as a marker of more aggressive tumors <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><a href="../genes/POLE.html">POLE</a>: no POLE-hypermutant (or MSI) tumors were reported, so the differences in TMB and deletions are not explained by hypermutator phenotypes <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li>Other rectal cancer driver genes altered in ≥10% of either cohort were compared (Figure 2D; eTables 4–5). The extracted text does not name any significant differences apart from APC and SMAD4 <a href="../papers/40100215.html">PMID:40100215</a>.</li>
</ul>
</section>
<section id="clinical-implications" class="level2">
<h2 class="anchored" data-anchor-id="clinical-implications">Clinical implications</h2>
<ul>
<li><strong>Prognosis:</strong> secondary rectal cancer after prostate RT carries a higher risk of distant recurrence (HR 12.68) and worse DFS (HR 6.16), independent of treatment differences. Local recurrence-free survival was similar to matched PRC <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>Treatment patterns:</strong> these patients were less likely to receive neoadjuvant chemoradiation, systemic chemotherapy, or curative-intent surgery. When they had surgery, they more often needed abdominoperineal resection or pelvic exenteration. Re-irradiation has become more accepted since 2014. Across all 33 NAT recipients (not only those re-irradiated), grade 3 toxic effects occurred in 18.2%, with no grade 4 or 5 events. Surgery was the only independent factor associated with OS <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>Immunotherapy hypothesis:</strong> frameshift indels can produce more immunogenic neoantigens. On that basis the authors “speculate that patients with [secondary rectal cancer] might be good candidates for immunotherapy.” They did not test this: the paper includes no immune checkpoint inhibitor outcome or immune-infiltrate data <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>Biologic distinctness:</strong> the authors read the clinical and genomic differences (lower TMB, APC wild-type, SMAD4 inactivation, excess deletions) as evidence that secondary rectal cancer is a biologically distinct entity. They do not treat it as sporadic rectal cancer arising in older men <a href="../papers/40100215.html">PMID:40100215</a>.</li>
</ul>
</section>
<section id="limitations-open-questions" class="level2">
<h2 class="anchored" data-anchor-id="limitations-open-questions">Limitations &amp; open questions</h2>
<ul>
<li><strong>Stated by the authors:</strong>
<ul>
<li>Retrospective accrual over about 3 decades, with heterogeneous diagnosis, treatment, and surveillance of both prostate and rectal cancer.</li>
<li>Radiation dose, delivery, and modality changed over time.</li>
<li>Some “secondary” cases may be sporadic rectal cancers not caused by radiation.</li>
<li>The genomic analyses were small (31 IMPACT, 17 WES) and underpowered.</li>
<li>Independent validation is needed <a href="../papers/40100215.html">PMID:40100215</a>.</li>
</ul></li>
<li><strong>Internal inconsistency:</strong> the Results say surgery was “the only factor associated with shorter OS (HR, 0.38 …)”. An HR below 1 means lower hazard, i.e., longer OS. The Discussion says only that surgery was “associated with OS”. Readers should interpret the direction from the HR <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>Follow-up vs endpoint:</strong> median follow-up for secondary cases was only 2.38 years (IQR 1.97–3.26), but the headline outcomes are 5-year Kaplan-Meier estimates. The OS gap is also confounded by a 23-year median age difference, although age was a matching variable in the outcome analysis <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>Sex imbalance in the genomic comparison:</strong> all secondary cases were men, while the 541 PRC comparators were 41.2% female. Sex was left out of the genomic matching because earlier rectal cancer profiling found no relevant sex differences <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>Anatomic confounding of APC (cross-paper):</strong> in the MSKCC rectal cohort of Chatila et al., <a href="../genes/APC.html">APC</a>/Wnt alteration frequency falls toward the anal verge (upper 92%, middle 90%, lower 77%; P&lt;.001) <a href="../papers/35970919.html">PMID:35970919</a>. Secondary tumors here were far more often distal (58.7% vs 22.5%), so some of the APC deficit could reflect location. The difference weakened but persisted against the 1:2 matched PRC set, which was matched on distance from the anal verge (48.4% vs 72.6%, P=.04) <a href="../papers/40100215.html">PMID:40100215</a>. This is recorded here, not resolved.</li>
<li><strong>Comparator provenance:</strong> the text does not say where the 541 PRC MSK-IMPACT and 28 PRC WES comparators came from. Whether they overlap with the MSKCC rectal cohorts of <a href="../papers/35970919.html">PMID:35970919</a> (<a href="../datasets/rectal_msk_2022.html">rectal_msk_2022</a>) is unknown. The reference list includes Chatila et al.&nbsp;<a href="../papers/35970919.html">PMID:35970919</a>, Zehir et al.&nbsp;<a href="../papers/28481359.html">PMID:28481359</a>, and Yaeger et al.&nbsp;<a href="../papers/29316426.html">PMID:29316426</a> among its MSK-IMPACT and colorectal genomics citations. It also cites the TCGA oncogenic signaling pathway framework <a href="../papers/29625050.html">PMID:29625050</a> for its pathway-level analysis.</li>
<li><strong>No radiation-specific signature:</strong> the WES analysis reports only SBS signatures (SBS1, SBS6, SBS15), and none differed by group. The extracted text does not say whether indel (ID) signatures were tested, even though frameshift and inframe deletions were enriched. The deletion comparisons use raw per-tumor variant counts <a href="../papers/40100215.html">PMID:40100215</a>.</li>
<li><strong>Missing cohort detail:</strong> 612 male controls vs a 604-man PRC reference set is unexplained. The end date of the accrual window is given as the non-existent “September 31, 2022” <a href="../papers/40100215.html">PMID:40100215</a>.</li>
</ul>
</section>
<section id="citations-from-this-paper-used-in-the-wiki" class="level2">
<h2 class="anchored" data-anchor-id="citations-from-this-paper-used-in-the-wiki">Citations from this paper used in the wiki</h2>
<p>Quotes are verbatim from the BioC-extracted text (no page numbers available). The abbreviation SRC has been replaced with “[secondary rectal cancer]” in brackets.</p>
<ul>
<li>“Patients with an adenocarcinoma located 12 cm or less from the anal verge that was diagnosed at least 5 years after completing RT for PC were considered to have [secondary rectal cancer]” (Methods, Patient Selection).</li>
<li>“Secondary rectal cancer was associated with worse DFS (hazard ratio [HR], 6.16 [95% CI, 2.10-18.07]; P &lt; .001) and DRFS (HR, 12.68 [95% CI, 3.06-52.47]; P &lt; .001) but was not associated with OS (HR, 1.95 [95% CI, 0.58-6.60]; P = .28).” (Results).</li>
<li>“Having surgery was the only factor associated with shorter OS (HR, 0.38 [95% CI, 0.16-0.88]; P = .02).” (Results).</li>
<li>“None of the patients were microsatellite instable or had a polymerase epsilon hypermutation.” (Results, Genomic Profile).</li>
<li>“Inactivating somatic alterations in the adenomatous polyposis coli (APC; OMIM 611731) gene were significantly less frequent in patients with [secondary rectal cancer] (15 of 31 [48.4%]) compared with patients with PRC (432 of 541 [79.9%]) and clinically matched patients with PRC (45 of 62 [72.6%]) (P &lt; .001 and P = .04, respectively).” (Results).</li>
<li>“SMAD4 (OMIM 600993) inactivation was more frequent in patients with [secondary rectal cancer] (8 of 31 [25.8%]) compared with patients with PRC (54 of 541 [10.0%]) (P = .01) and clinically matched patients with PRC (5 of 62 [8.1%]) (P = .03)” (Results).</li>
<li>“Tumors from patients with [secondary rectal cancer] had more frameshift deletions than tumors from patients with PRC (median, 5.0 [IQR, 4.0-9.0] vs 2.5 [IQR, 1.0-4.2] variants; P &lt; .001)” (Results, WES).</li>
<li>“No significant differences were observed in terms of any of the signatures from the COSMIC catalog between the groups with [secondary rectal cancer] and PRC, including the SBS6 and SBS15 signatures associated with defective mismatch repair” (Results, WES).</li>
<li>“None of the 11 patients treated with NAT for rectal cancer until 2014 received RT, whereas 14 of 22 patients with [secondary rectal cancer] treated after that year (63.6%) received re-irradiation treatment.” (Discussion).</li>
<li>“Based on these findings, it is tempting to speculate that patients with [secondary rectal cancer] might be good candidates for immunotherapy, which could provide an additional treatment option for this patient population.” (Discussion).</li>
<li>“our genomic analyses were limited by small sample sizes, which resulted in restricted statistical power.” (Limitations).</li>
</ul>
<p><em>This page was processed by <strong>crosslinker</strong> on <strong>2026-09-11</strong>.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jim-bo\.github\.io\/cbio-kb\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/jim-bo/cbio-kb/edit/main/papers/40100215.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/jim-bo/cbio-kb/blob/main/papers/40100215.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div></div></footer></body></html>