<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Clinical utility and tissue concordance of circulating tumor DNA in pancreatic ductal adenocarcinoma – cbio-kb</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-89af0c2d685ccb09a4d7d65decb66752.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../site-styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">cbio-kb</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../papers/index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../genes/index.html"> 
<span class="menu-text">Genes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cancer_types/index.html"> 
<span class="menu-text">Cancers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../datasets/index.html"> 
<span class="menu-text">Datasets</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../drugs/index.html"> 
<span class="menu-text">Drugs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../methods/index.html"> 
<span class="menu-text">Methods</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../themes/index.html"> 
<span class="menu-text">Themes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../experiments/index.html"> 
<span class="menu-text">Experiments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ask.html"> 
<span class="menu-text">Ask</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tldr" id="toc-tldr" class="nav-link active" data-scroll-target="#tldr">TL;DR</a></li>
  <li><a href="#cohort-data" id="toc-cohort-data" class="nav-link" data-scroll-target="#cohort-data">Cohort &amp; data</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings">Key findings</a></li>
  <li><a href="#genes-alterations" id="toc-genes-alterations" class="nav-link" data-scroll-target="#genes-alterations">Genes &amp; alterations</a></li>
  <li><a href="#clinical-implications" id="toc-clinical-implications" class="nav-link" data-scroll-target="#clinical-implications">Clinical implications</a></li>
  <li><a href="#limitations-open-questions" id="toc-limitations-open-questions" class="nav-link" data-scroll-target="#limitations-open-questions">Limitations &amp; open questions</a></li>
  <li><a href="#citations-from-this-paper-used-in-the-wiki" id="toc-citations-from-this-paper-used-in-the-wiki" class="nav-link" data-scroll-target="#citations-from-this-paper-used-in-the-wiki">Citations from this paper used in the wiki</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/jim-bo/cbio-kb/edit/main/papers/40511613.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/jim-bo/cbio-kb/blob/main/papers/40511613.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Clinical utility and tissue concordance of circulating tumor DNA in pancreatic ductal adenocarcinoma</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Fergus Keane </p>
             <p>Lily V Saadat </p>
             <p>Catherine A O’Connor </p>
             <p>Joanne F Chou </p>
             <p>Anita S Bowman </p>
             <p>Fei Xu </p>
             <p>Fionnuala Crowley </p>
             <p>Neha Debnath </p>
             <p>Joshua D Schoenfeld </p>
             <p>Anupriya Singhal </p>
             <p>Drew Moss </p>
             <p>Darren Cowzer </p>
             <p>Emily Harrold </p>
             <p>Wungki Park </p>
             <p>Anna Varghese </p>
             <p>Fiyinfolu Balogun </p>
             <p>Kenneth H Yu </p>
             <p>Alice Zervoudakis </p>
             <p>Marinela Capanu </p>
             <p>Michael F Berger </p>
             <p>Alice C Wei </p>
             <p>Angela Rose Brannon </p>
             <p>Eileen M O’Reilly </p>
          </div>
  </div>
    
  
    
    <div>
    <div class="quarto-title-meta-heading">Doi</div>
    <div class="quarto-title-meta-contents">
      <p class="doi">
        <a href="https://doi.org/10.1093/jnci/djaf139">10.1093/jnci/djaf139</a>
      </p>
    </div>
  </div>
  </div>
  


</header>


<p><strong>PMID:</strong> 40511613 · <strong>DOI:</strong> 10.1093/jnci/djaf139 · <strong>Journal:</strong> Journal of the National Cancer Institute (2025)</p>
<section id="tldr" class="level2">
<h2 class="anchored" data-anchor-id="tldr">TL;DR</h2>
<p>Keane, O’Reilly and colleagues at Memorial Sloan Kettering (MSK) looked back at 414 patients with pancreatic ductal adenocarcinoma (<a href="../cancer_types/PAAD.html">PAAD</a>) who had at least one plasma sample sequenced with the 129-gene <a href="../methods/ACCESS129.html">MSK-ACCESS</a> ctDNA assay between August 2019 and July 2022. ctDNA was detected in 56% of patients overall, and detection rose with stage: 34% in stage I–II, 38% in stage III and 75% in stage IV. In stage IV, detection was higher with liver metastases (82% vs 52%, P&lt;.001), with 2 or more organs involved (76% vs 38%, P=.025), and with higher CA19-9, CEA and alkaline phosphatase. In untreated stage IV patients with tissue sequenced at the same time (MSK-IMPACT <a href="../methods/IMPACT468.html">IMPACT468</a>/<a href="../methods/IMPACT505.html">IMPACT505</a>, n=62), ctDNA agreed closely with tissue: the critical success index (CSI) was 93.1% for <a href="../genes/KRAS.html">KRAS</a>, 84.3% for <a href="../genes/TP53.html">TP53</a>, 89.5% for <a href="../genes/CDKN2A.html">CDKN2A</a> and 63.6% for <a href="../genes/SMAD4.html">SMAD4</a>. Agreement was much lower in untreated stage I–III disease (n=29; <a href="../genes/KRAS.html">KRAS</a> CSI 39.3%). In untreated stage IV, median overall survival (OS) was 10 months with detectable ctDNA and 19 months without, but the difference was not significant (P=.10). The authors conclude that ctDNA is a complementary adjunct to tissue sequencing, not a replacement <a href="../papers/40511613.html">PMID:40511613</a>.</p>
</section>
<section id="cohort-data" class="level2">
<h2 class="anchored" data-anchor-id="cohort-data">Cohort &amp; data</h2>
<ul>
<li><strong>Patients:</strong> 414 patients with PDAC and at least 1 ctDNA sample at MSK, August 2019 – July 2022, identified under IRB protocols 12-245 and 19-242. Clinical and survival data came from a prospectively maintained institutional database and medical record review <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Stage at ctDNA testing:</strong>
<ul>
<li>stage I–II: n=115 (28%)</li>
<li>stage III: n=88 (21%)</li>
<li>stage IV: n=211 (51%)</li>
<li>Stage I–III includes both resected and unresected tumors <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
<li><strong>Demographics:</strong>
<ul>
<li>Female: 50% (n=208).</li>
<li>White: 324 patients. The text gives this as 78%; Table 1 gives 83% of patients with known race.</li>
<li>Smoking: 32% former smokers (n=133), 5% current smokers (n=22).</li>
<li>Tumor location: head 53%, body 25%, tail 23%.</li>
<li>55% (n=227) had received treatment before ctDNA testing and 44% (n=187) were treatment-naïve <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
<li><strong>Analytic subcohorts:</strong>
<ul>
<li>untreated stage IV (n=120)</li>
<li>untreated stage III (n=38)</li>
<li>post-resection before adjuvant therapy (n=29)</li>
<li>untreated stage I–III with matched tissue (n=29 of 68)</li>
<li>untreated stage IV with matched tissue (n=62 of 120)</li>
<li>all tissue–ctDNA matched pairs (n=131)</li>
<li>“Untreated” means no prior chemotherapy, radiation or surgery in any disease setting. “Matched” means tissue and ctDNA collected within 1 month with no therapy in between <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
<li><strong>ctDNA assay:</strong> <a href="../methods/ACCESS129.html">MSK-ACCESS</a> version 1 is a New York State–approved, hybridization-capture, deep-sequencing assay covering 129 genes. It sequences matched buffy-coat DNA to filter out germline events.
<ul>
<li>“ctDNA detected” means at least 1 variant, copy-number alteration or structural variant.</li>
<li>De novo calls need 3 duplex fragments for a hotspot variant and 5 for a non-hotspot variant.</li>
<li>If a prior tissue or plasma sample supports the variant, the threshold drops to 1 duplex or 2 simplex fragments (tumor-informed calling).</li>
<li>In the 131 matched pairs, the team also ran GetBaseCountsMultiSample v1.2.5 to find sub-threshold empirical calls <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
<li><strong>Tissue assay:</strong> MSK-IMPACT with 468 genes (v6, <a href="../methods/IMPACT468.html">IMPACT468</a>) or 505 genes (v7, <a href="../methods/IMPACT505.html">IMPACT505</a>) on FFPE tumor with matched buffy coat. Filters were depth ≥20, alternate allele count ≥8, and VAF ≥2% for hotspot or ≥5% for non-hotspot variants <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Statistics:</strong>
<ul>
<li>Fisher exact test for ctDNA positivity vs disease subgroups.</li>
<li>Wilcoxon rank-sum test for serum biomarkers.</li>
<li><a href="../methods/kaplan-meier.html">Kaplan–Meier</a> OS, measured from the ctDNA blood draw.</li>
<li>Overall agreement = (TP+TN)/all. CSI = TP/(TP+FN+FP). CSI leaves out true negatives, which would overstate agreement for rarely mutated genes.</li>
<li>Analyses used R 4.3.2, with 2-sided P&lt;.05 <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
<li><strong>Data:</strong> deposited in cBioPortal as <a href="../datasets/pancreas_ctdna_msk_2025.html">pancreas_ctdna_msk_2025</a> <a href="../papers/40511613.html">PMID:40511613</a>. The cBioPortal study record (not the paper) lists 412 samples on hg19.</li>
</ul>
</section>
<section id="key-findings" class="level2">
<h2 class="anchored" data-anchor-id="key-findings">Key findings</h2>
<p><strong>ctDNA detection by stage</strong> - <strong>Whole cohort:</strong> 230/414 (56%) had at least 1 variant detected <a href="../papers/40511613.html">PMID:40511613</a>. - <strong>By stage:</strong> - stage I–II: 39/115 (34%) - stage III: 33/88 (38%) - stage IV: 158/211 (75%) - <a href="../papers/40511613.html">PMID:40511613</a> - <strong>Treatment-naïve patients:</strong> 13/38 (34%) with untreated stage III vs 105/120 (88%) with untreated stage IV <a href="../papers/40511613.html">PMID:40511613</a>.</p>
<p><strong>Stage IV detection by disease burden and metastatic site (n=211, Table 2)</strong> - <strong>Organs involved:</strong> detection was 155/203 (76%) with ≥2 organs vs 3/8 (38%) with &lt;2 organs (P=.025) <a href="../papers/40511613.html">PMID:40511613</a>. - <strong>Number of disease sites:</strong> - 2–3 sites (n=170): 124 (73%) - 4 sites (n=22): 20 (91%) - ≥5 sites (n=11): 100% - In the untreated stage IV subcohort, all 18 patients with ≥4 sites had detectable ctDNA <a href="../papers/40511613.html">PMID:40511613</a>. - <strong>By metastatic site (present vs absent):</strong> - Liver: 131/159 (82%) vs 27/52 (52%), P&lt;.001 - Lung: 83% vs 72%, P=.13 - Peritoneum: 68% vs 78%, P=.2 - Only liver involvement reached significance <a href="../papers/40511613.html">PMID:40511613</a>. - <strong>Single-site metastasis, all stage IV:</strong> - liver-only (n=81): 63 (78%) - peritoneum-only (n=16): 10 (63%) - lung-only (n=9): 5 (56%) - <a href="../papers/40511613.html">PMID:40511613</a> - <strong>Single-site metastasis, untreated stage IV:</strong> - liver-only (n=43): 91% - lung-only (n=4): 100% - peritoneal-only (n=9): 82% - <a href="../papers/40511613.html">PMID:40511613</a> - <strong>Serum markers (ctDNA detected vs not detected in stage IV; all P&lt;.001):</strong> - CA19-9: median 2286 vs 128 U/mL - CEA: 10 vs 5 ng/mL - Alkaline phosphatase: 143 vs 95 - Higher CA19-9, CEA and alkaline phosphatase with detectable ctDNA were also seen across all stages (Table S2) <a href="../papers/40511613.html">PMID:40511613</a>.</p>
<p><strong>Survival (exploratory)</strong> - <strong>Untreated stage IV (n=120):</strong> median OS 10 months (95% CI 6.9–14) with detectable ctDNA vs 19 months (95% CI 13–NR) with undetectable ctDNA (n=15), P=.10. The authors attribute the lack of significance to the small ctDNA-negative group <a href="../papers/40511613.html">PMID:40511613</a>. - <strong>Untreated stage III (n=38):</strong> OS did not differ significantly by ctDNA status. The Results and Discussion give conflicting estimates (see Limitations) <a href="../papers/40511613.html">PMID:40511613</a>. - <strong>Post-resection, before adjuvant chemotherapy (n=29):</strong> median OS 30 months with detectable ctDNA (n=5) vs not reached without (n=24), P=.4 <a href="../papers/40511613.html">PMID:40511613</a>.</p>
<p><strong>Tissue–ctDNA concordance (critical success index)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Gene</th>
<th>Untreated stage I–III (n=29 matched)</th>
<th>Untreated stage IV (n=62 matched)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="../genes/KRAS.html">KRAS</a></td>
<td>39.3%</td>
<td>93.1%</td>
</tr>
<tr class="even">
<td><a href="../genes/TP53.html">TP53</a></td>
<td>39.1%</td>
<td>84.3%</td>
</tr>
<tr class="odd">
<td><a href="../genes/CDKN2A.html">CDKN2A</a></td>
<td>33.3%</td>
<td>89.5%</td>
</tr>
<tr class="even">
<td><a href="../genes/SMAD4.html">SMAD4</a></td>
<td>12.5%</td>
<td>63.6%</td>
</tr>
</tbody>
</table>
<p>Source for the table: <a href="../papers/40511613.html">PMID:40511613</a>.</p>
<ul>
<li><strong>Why early-stage concordance is low:</strong> the authors cite lower tumor cellularity, known difficulty obtaining tissue from primary PDAC, and lower tumor DNA shedding, which is already low in PDAC compared with cancers such as colorectal. Differences in vascularization may also contribute <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul>
<p><strong>Somatic profile and KRAS alleles</strong> - <strong>Most common genes in ctDNA-positive patients (n=230):</strong> - <a href="../genes/KRAS.html">KRAS</a>: 68% - <a href="../genes/TP53.html">TP53</a>: 53% - <a href="../genes/CDKN2A.html">CDKN2A</a>: 12% - <a href="../genes/SMAD4.html">SMAD4</a>: 10% - These rates are lower than expected in tissue, which the authors attribute to the inclusion of early-stage patients <a href="../papers/40511613.html">PMID:40511613</a>. - <strong>KRAS alleles:</strong> 170/414 (41%) had a KRAS variant in ctDNA. Of these: - G12D: n=80 (47%) - G12V: n=53 (31%) - G12R: n=25 (15%) - <a href="../papers/40511613.html">PMID:40511613</a> - <strong>Mean KRAS VAF by stage:</strong> - stage I: 0.038 - stage II: 0.024 - stage III: 0.066 - stage IV: 0.091 - <a href="../papers/40511613.html">PMID:40511613</a> - <strong>KRAS allele distribution in the 131 matched pairs</strong> was numerically similar in tissue and ctDNA: - tissue: G12D 46%, G12V 27%, G12R 17% - ctDNA: G12D 56%, G12V 25%, G12R 13% - <a href="../papers/40511613.html">PMID:40511613</a></p>
</section>
<section id="genes-alterations" class="level2">
<h2 class="anchored" data-anchor-id="genes-alterations">Genes &amp; alterations</h2>
<ul>
<li><strong><a href="../genes/KRAS.html">KRAS</a>:</strong>
<ul>
<li>Most frequently detected ctDNA alteration: 68% of ctDNA-positive patients and 41% of the whole cohort.</li>
<li>Allele mix: G12D 47%, G12V 31%, G12R 15%.</li>
<li>Mean VAF was highest in stage IV (0.091).</li>
<li>Tissue–ctDNA CSI was 93.1% in untreated stage IV vs 39.3% in untreated stage I–III.</li>
<li>In one patient whose tumor could not be sequenced, ctDNA found KRAS G12C at progression, which allowed enrollment in a KRAS G12C inhibitor trial <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
<li><strong><a href="../genes/TP53.html">TP53</a>:</strong> 53% of ctDNA-positive patients. CSI 84.3% in untreated stage IV vs 39.1% in untreated stage I–III <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong><a href="../genes/CDKN2A.html">CDKN2A</a>:</strong> 12% of ctDNA-positive patients. CSI 89.5% in untreated stage IV vs 33.3% in untreated stage I–III <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong><a href="../genes/SMAD4.html">SMAD4</a>:</strong> 10% of ctDNA-positive patients. CSI 63.6% in untreated stage IV vs 12.5% in untreated stage I–III, the lowest concordance of the four genes <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong><a href="../genes/MSH2.html">MSH2</a>:</strong> case report of a patient with Lynch syndrome and microsatellite-instable PDAC carrying a germline pathogenic <a href="../genes/MSH2.html">MSH2</a> variant.
<ul>
<li>Before immune checkpoint blockade, ctDNA showed 14 variants.</li>
<li>The patient had an excellent clinical, radiographic and biochemical response, with marked immune-related toxicity.</li>
<li>After 5 months of immune checkpoint blockade, ctDNA was undetectable and stayed undetectable on serial sampling. This clearance helped the team decide to safely withhold further checkpoint blockade <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
</ul>
</section>
<section id="clinical-implications" class="level2">
<h2 class="anchored" data-anchor-id="clinical-implications">Clinical implications</h2>
<ul>
<li><strong>Stage IV:</strong> ctDNA from <a href="../methods/ACCESS129.html">MSK-ACCESS</a> is highly concordant with tissue NGS in untreated stage IV PDAC, especially for KRAS. The authors argue that faster KRAS allele results will guide treatment choice as KRAS-directed and allele-specific inhibitor therapies arrive <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Early stage:</strong> because concordance is low in stage I–III, the authors say ctDNA needs better sensitivity there. They consider tissue NGS combined with ctDNA optimal, even though localized PDAC is where tissue is hardest to obtain <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Who benefits most:</strong> ctDNA testing was most informative in treatment-naïve stage IV disease, liver metastases, higher disease burden and elevated tumor markers. A negative ctDNA result should be interpreted with caution in patients without liver metastases; peritoneal-only disease may yield less because of the plasma–peritoneal barrier <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Prognosis:</strong> detectable ctDNA was linked to numerically shorter OS in untreated stage IV (10 vs 19 months) and in the post-resection setting (30 months vs not reached). Neither difference was significant, and the authors call the survival analysis exploratory. They still support ctDNA as a marker of disease burden and a prognosticator <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Tumor-informed calling:</strong> when tissue NGS results already exist, MSK-ACCESS uses a lower calling threshold and effectively becomes a tumor-informed assay. The authors say automated integration of prior MSK-IMPACT results raises sensitivity, and matched white-blood-cell sequencing raises specificity and separates clonal hematopoiesis from true ctDNA. For these points they cite the MSK-ACCESS validation study <a href="../papers/34145282.html">PMID:34145282</a> and MSK’s ctDNA-guided <a href="../cancer_types/NSCLC.html">NSCLC</a> study <a href="../papers/36357680.html">PMID:36357680</a> <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Monitoring:</strong> serial ctDNA changed management in individual patients. The main example is ctDNA clearance guiding the decision to withhold immune checkpoint blockade in the MSH2-associated MSI case <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul>
</section>
<section id="limitations-open-questions" class="level2">
<h2 class="anchored" data-anchor-id="limitations-open-questions">Limitations &amp; open questions</h2>
<ul>
<li><strong>Limitations the authors state:</strong> single tertiary center; retrospective design; limited demographic diversity; heterogeneity in stage, disease burden and ctDNA sampling time, which leaves some subgroups small (e.g., 5 ctDNA-positive post-resection patients; 15 ctDNA-negative untreated stage IV patients). No external cohort has the detailed clinical and genomic annotation needed to validate the concordance results. No data compare MSK-ACCESS with other commercial panels <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Internal inconsistencies in the extracted text (recorded, not resolved):</strong>
<ul>
<li><strong>Table 1:</strong> the ctDNA status rows appear to have their labels swapped. Table 1 lists 184 “detected” / 230 “not detected” overall and 53 detected / 158 not detected in stage IV. The abstract, text and Table 2 give 230 (56%) detected overall and 158/211 (75%) detected in stage IV. This page uses the text and Table 2 figures <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Untreated stage IV:</strong> one passage gives 105/120 with detectable ctDNA; the survival passage gives n=115 detectable and 15 undetectable <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Untreated stage III survival:</strong>
<ul>
<li>Results: 15 months (95% CI 15–NR) with ctDNA vs 22 months (95% CI 22–NR) without; ctDNA-negative n printed as 75; P printed as “04”.</li>
<li>Discussion: not reached (95% CI 15 months–NR) vs 22 months (95% CI 14–NR), P=.40, ctDNA-negative n=25.</li>
<li>The authors call the trend “unexpected” and put it down to small numbers <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
<li><strong>Post-resection:</strong> the ctDNA-positive median OS of 30 months is reported with a 95% CI of “33 months to not reached”, so the lower bound exceeds the point <a href="../methods/estimate.html">estimate</a> <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Liver metastases:</strong> the text describes the 159 patients with 131 (82%) detected as “liver metastasis and another metastatic site”. Table 2 uses the same 159/131 for all patients with liver metastases, and the text separately lists 81 liver-only patients <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
<li><strong>Small comparator group:</strong> the ≥2 vs &lt;2 organ comparison (76% vs 38%) rests on only 8 patients with &lt;2 organs involved <a href="../papers/40511613.html">PMID:40511613</a>.</li>
<li><strong>Cross-paper note on concordance:</strong>
<ul>
<li>The pan-cancer MSK-ACCESS validation <a href="../papers/34145282.html">PMID:34145282</a> (<a href="../datasets/msk_access_2021.html">msk_access_2021</a>) reported that 59% of mutations in overlapping regions were shared between tissue and plasma. Its discordance tracked the time between tissue and blood collection.</li>
<li>This study required matched samples within 1 month with no intervening therapy and reports per-gene CSI rather than a pooled shared fraction.</li>
<li>Because of these design differences, the two studies’ concordance figures cannot be compared directly <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
<li><strong>Open questions:</strong>
<ul>
<li>Whether ctDNA kinetics predict response in PDAC. Serial sampling was not a study focus.</li>
<li>How much the lowered, tumor-informed calling threshold raises the stage IV CSI compared with de novo calling.</li>
<li>Whether tumor-agnostic ctDNA can reach clinically useful sensitivity in stage I–III disease <a href="../papers/40511613.html">PMID:40511613</a>.</li>
</ul></li>
</ul>
</section>
<section id="citations-from-this-paper-used-in-the-wiki" class="level2">
<h2 class="anchored" data-anchor-id="citations-from-this-paper-used-in-the-wiki">Citations from this paper used in the wiki</h2>
<ul>
<li>“Concordance between ctDNA and tissue is high for patients with untreated metastatic disease, notably for detection of KRAS variants.” (p.&nbsp;1848, Abstract) <a href="../papers/40511613.html">PMID:40511613</a></li>
<li>“Higher rates of ctDNA detection were observed in patients with liver metastases vs without (82% vs 52%, P&lt;.001).” (p.&nbsp;1848, Abstract) <a href="../papers/40511613.html">PMID:40511613</a></li>
<li>“In this group with matched samples, the critical success index between ctDNA and tissue was 93.1% for KRAS variants, 84.3% for <a href="../genes/TP53.html">TP53</a>, 89.5% for <a href="../genes/CDKN2A.html">CDKN2A</a>, and 63.6% for <a href="../genes/SMAD4.html">SMAD4</a>” (p.&nbsp;1852) <a href="../papers/40511613.html">PMID:40511613</a></li>
<li>“In this group, the critical index concordance was 39.3% for KRAS variants, 39.1% for TP53, 33.3% for CDKN2A, and 12.5% for SMAD4” (p.&nbsp;1852, untreated stage I–III) <a href="../papers/40511613.html">PMID:40511613</a></li>
<li>“The lower concordance in stage I-III is likely due to lower tumor cellularity and known limitations of tissue acquisition for primary pancreas ductal adenocarcinoma and decreased tumor shedding” (p.&nbsp;1854) <a href="../papers/40511613.html">PMID:40511613</a></li>
<li>“One patient in our cohort for whom tumor-based sequencing had not previously been feasible had a KRAS G12C variant identified by ctDNA at the time of disease progression, facilitating enrollment on a clinical trial of KRAS G12C inhibitor.” (pp.&nbsp;1853–1854) <a href="../papers/40511613.html">PMID:40511613</a></li>
<li>“Our results support the use of ctDNA as a complementary adjunct to tissue-based sequencing.” (p.&nbsp;1855) <a href="../papers/40511613.html">PMID:40511613</a></li>
</ul>
<p><em>This page was processed by <strong>crosslinker</strong> on <strong>2026-09-11</strong>.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jim-bo\.github\.io\/cbio-kb\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/jim-bo/cbio-kb/edit/main/papers/40511613.md" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/jim-bo/cbio-kb/blob/main/papers/40511613.md" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div></div></footer></body></html>